# Generated by Django 5.0.6 on 2024-06-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_userprofile_interests_userprofile_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Movie"),
                    ("b", "Drama"),
                    ("c", "Concert"),
                    ("d", "Party"),
                    ("e", "Art"),
                    ("f", "Uncategorized"),
                ],
                max_length=100,
            ),
        ),
    ]
