# Generated by Django 5.0.6 on 2024-06-21 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_userprofile_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="UserBadge",
        ),
    ]
